Repository CS540-22/GLOC, pull requests merged in 2022-04, with the labels that each got.

#35 Backend Upgrades
  api/Pipfile
  api/Pipfile.lock
  api/app.py
  api/cloc.sh
  api/gunicorn_conf.py
  api/requirements.txt
  api/worker.py
  api/wsgi.py
  cluster/docker/Dockerfile
  cluster/docker/build.sh
  cluster/k8s/cloc-deployment.yaml
  cluster/k8s/gh-runner/gh-runner.yaml
  cluster/k8s/gh-runner/gh-values.yaml
  cluster/k8s/redis/redis-config.yaml
  cluster/k8s/redis/redis-statefulset.yaml
  cluster/k8s/redis/redis-svc.yaml
Labels: bug, enhancement

#36 Minor fixes
  api/app.py
  cluster/docker/build.sh
Labels: bug

#39 UI updates
  .gitignore
  gloc_ui/lib/data/ClocJob.dart
  gloc_ui/lib/data/ClocRequest.dart
  gloc_ui/lib/data/ClocResult.dart
  gloc_ui/lib/main.dart
  gloc_ui/lib/widgets/DetailsPage.dart
  gloc_ui/lib/widgets/HistoryPage.dart
  gloc_ui/lib/widgets/HomePage.dart
  gloc_ui/lib/widgets/LangaugePieChart.dart
  gloc_ui/lib/widgets/LoadingPage.dart
  gloc_ui/pubspec.lock
  gloc_ui/pubspec.yaml
Labels: enhancement

#45 Add dropzone to home page
  .gitignore
  gloc_ui/lib/widgets/HomePage.dart
  gloc_ui/pubspec.lock
  gloc_ui/pubspec.yaml
Labels: enhancement

#46 Add download widget
  gloc_ui/lib/widgets/DetailsPage.dart
Labels: enhancement

#48 Front-end and back-end updates
  api/Pipfile
  api/Pipfile.lock
  api/app.py
  api/requirements.txt
  cluster/docker/api/Dockerfile
  cluster/docker/api/build.sh
  cluster/docker/build.sh
  cluster/docker/gloc_ui/Dockerfile
  cluster/docker/gloc_ui/build.sh
  cluster/k8s/gloc-ui-deployment.yaml
  gloc_ui/lib/widgets/HomePage.dart
  gloc_ui/lib/widgets/LoadingPage.dart
Labels: enhancement

#49 Add advanced configuration
  gloc_ui/lib/data/ClocRequest.dart
  gloc_ui/lib/widgets/HomePage.dart
Labels: enhancement
